// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0k11tgOaHN4iPcgNEZTG6nNrH161SY54',
    appId: '1:894912905678:web:861955befd385d582cab9f',
    messagingSenderId: '894912905678',
    projectId: 'bharat-sports-olymps',
    authDomain: 'bharat-sports-olymps.firebaseapp.com',
    storageBucket: 'bharat-sports-olymps.firebasestorage.app',
    measurementId: 'G-MPYJJQE3JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx9NZh3SXeqrRsmrFtzE12m7o_ZLTlibQ',
    appId: '1:894912905678:android:564386795f83d0c22cab9f',
    messagingSenderId: '894912905678',
    projectId: 'bharat-sports-olymps',
    storageBucket: 'bharat-sports-olymps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxmqeeHJgxvAJv-AIM0t1FTu1gXIsaYc',
    appId: '1:894912905678:ios:4bab658d08bede732cab9f',
    messagingSenderId: '894912905678',
    projectId: 'bharat-sports-olymps',
    storageBucket: 'bharat-sports-olymps.firebasestorage.app',
    iosBundleId: 'com.example.sportOlymps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxmqeeHJgxvAJv-AIM0t1FTu1gXIsaYc',
    appId: '1:894912905678:ios:4bab658d08bede732cab9f',
    messagingSenderId: '894912905678',
    projectId: 'bharat-sports-olymps',
    storageBucket: 'bharat-sports-olymps.firebasestorage.app',
    iosBundleId: 'com.example.sportOlymps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0k11tgOaHN4iPcgNEZTG6nNrH161SY54',
    appId: '1:894912905678:web:e23d69d52e686b652cab9f',
    messagingSenderId: '894912905678',
    projectId: 'bharat-sports-olymps',
    authDomain: 'bharat-sports-olymps.firebaseapp.com',
    storageBucket: 'bharat-sports-olymps.firebasestorage.app',
    measurementId: 'G-HLN1W28G67',
  );
}
